# Generated by Django 5.0.4 on 2024-04-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_language_fk_rawtext_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtext',
            name='language_char',
        ),
    ]
