# Generated by Django 5.0.4 on 2024-04-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_rawtext_language_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMTextWithTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('original_prompt', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.language')),
            ],
        ),
    ]
