# Generated by Django 6.0.3 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    """Make prompt text a stable fixture identifier."""

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="prompt_text",
            field=models.TextField(unique=True),
        ),
    ]
