# Generated by Django 5.0.4 on 2024-04-20 13:35

from django.db import migrations


def add_languages(apps, schema_editor):
    language = apps.get_model("mainApp", "Language")
    rawText = apps.get_model("mainApp", "RawText")
    language_names = set(rawText.objects.all().values_list("language_char", flat=True))
    for name in language_names:
        language.objects.create(language_name=name)


def link_languages(apps, schema_editor):
    language = apps.get_model("mainApp", "Language")
    rawText = apps.get_model("mainApp", "RawText")
    for item in rawText.objects.all():
        language = language.objects.get(language_name=item.language_char)
        item.language_fk = language
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_language_rename_language_rawtext_language_char_and_more"),
    ]

    operations = [
        migrations.RunPython(add_languages),
        migrations.RunPython(link_languages),
        migrations.RenameField(
            model_name="rawtext",
            old_name="language_fk",
            new_name="language",
        ),
    ]
