# Generated by Django 5.0.4 on 2024-04-23 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0005_llmtextwithtranslation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawText",
        ),
    ]
